import { ClerkProvider, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="about-page bg-stretch bg-center">
          <div className="bg-center">
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>
            <h1 className="flex items-center justify-center text-5xl font-bold">
              Welcome, To the World of Fitness
            </h1>
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
